trigger:
- main

pool:
  DevOps-Poool

variables: 
  workingDirectory: 'environment/dev'
  provider: 'azurerm'

steps:
- task: TerraformInstaller@1
  displayName: Terraform Installer
  inputs: 
    terraformVersion: latest

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: "$(provider)"
    command: 'init'
    workingDirectory: "$(workingDirectory)"
    backendServiceArm: 'Service Connection'
    backendAzureRmResourceGroupName: 'rg-bhavya'
    backendAzureRmStorageAccountName: 'bhavyastorageacc'
    backendAzureRmContainerName: 'bhavyacontainer'
    backendAzureRmKey: 'bhavya.tfstate'
  
- task: TerraformTask@5
  displayName: Terraform Validate
  inputs:
    provider: "$(provider)"
    command: 'validate'
    workingDirectory: "$(workingDirectory)"

- task: TerraformTask@5
  displayName: Terraform Plan
  inputs:
    provider: "$(provider)"
    command: 'plan'
    workingDirectory: "$(workingDirectory)"
    environmentServiceNameAzureRM: 'Service Connection'

- task: TerraformTask@5
  displayName: Terraform Apply
  inputs:
    provider: "$(provider)"
    command: 'apply'
    workingDirectory: "$(workingDirectory)"
    environmentServiceNameAzureRM: 'Service Connection'