trigger:
- main

pool:
  Agent-Poool

steps:
- task: TerraformInstaller@1
  displayName: Terraform Installer
  inputs: 
    terraformVersion: 1.12.2

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'environment/dev'
    backendServiceArm: 'Service Connection'
    backendAzureRmResourceGroupName: 'rg-bhavya'
    backendAzureRmStorageAccountName: 'bhavyastorageacc'
    backendAzureRmContainerName: 'bhavyacontainer'
    backendAzureRmKey: 'bhavya.tfstate'
  
- task: TerraformTask@5
  displayName: Terraform Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: 'environment/dev'

- task: TerraformTask@5
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'environment/dev'
    environmentServiceNameAzureRM: 'Service Connection'

- task: TerraformTask@5
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'environment/dev'
    environmentServiceNameAzureRM: 'Service Connection'